# Generated by Django 3.2.6 on 2022-03-15 22:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ukvita', '0003_daynumber_userip_visitnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.TextField(verbose_name='Имя')),
                ('first_name', models.TextField(verbose_name='Фамилия')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('message', models.TextField(verbose_name='Обращение')),
                ('day', models.DateField(default=django.utils.timezone.now, verbose_name='Дата обращения')),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='day',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата обращения'),
        ),
    ]
